# mybatis
mybatis-plus:
  type-aliases-package: 'cn.pings.service.api.sys.**.entity'
  mapper-locations: 'classpath:mapper/**/*.xml'

  # 全局策略配置
  global-config:
    # 更新mapper的xml，自动刷新，生产环境请勿打开
    refresh: true
    db-config:
      # 表的前缀名
      table-prefix: sys_
      # id自动增长
      id-type: auto
  configuration:
    # 驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true

# Service version
sys:
  service:
    version: 0.0.1

---

# spring
spring:
  profiles: dev

  # redis
  redis:
    host: '112.74.169.154'
    password: '123456'
    port: 6379

  # 数据源
  datasource:
    type: 'com.alibaba.druid.pool.DruidDataSource'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://112.74.169.154:13306/pings_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
    username: 'root'
    password: '123456'
    # druid设置
    druid:
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      # 配置监控统计拦截的filters
      filters: 'wall,stat'

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.service.sys

  # ApplicationConfig Bean
  application:
   id: pings-service-sys
   name: pings-service-sys

  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  # RegistryConfig Bean
  registry:
    id: service-sys
    address: zookeeper://112.74.169.154:2181

---

# spring
spring:
  profiles: prod

  # redis
  redis:
    host: 'redis_test'
    password: '123456'
    port: 6379

  # 数据源
  datasource:
    type: 'com.alibaba.druid.pool.DruidDataSource'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://pings_sys_test:13306/pings_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
    username: 'root'
    password: '123456'
    # druid设置
    druid:
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      # 配置监控统计拦截的filters
      filters: 'wall,stat'

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.service.sys

  # ApplicationConfig Bean
  application:
   id: pings-service-sys
   name: pings-service-sys

  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  # RegistryConfig Bean
  registry:
    id: service-sys
    address: zookeeper://zk_test:2181