# spring
spring:
  profiles: dev

  # redis
  redis:
    host: '112.74.169.154'
    password: '123456'
    port: 6379
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数(负值表示没有限制)
        max-active: 8
        # 连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.web.admin

  # ApplicationConfig Bean
  application:
   id: pings-web-admin
   name: pings-web-admin

  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  # RegistryConfig Bean
  registry:
    id: client-admin
    address: zookeeper://112.74.169.154:2181

# sys config
sys:
  # Service version
  service:
    version: 0.0.1
  jwt:
    secret: ==SFddfenfV2FuZzkyNjQ1NGRTQkFQSUpXVA==
     # 访问令牌过期时长(分钟)，<= 0时，使用默认配置5分钟
    access-token:
      expire-time: 10
    # 刷新令牌过期时长(分钟)，<= 0时，使用默认配置60分钟
    refresh-token:
      expire-time: 60

---

# spring
spring:
  profiles: prod

  # redis
  redis:
    host: 'redis_test'
    password: '123456'
    port: 6379
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数(负值表示没有限制)
        max-active: 8
        # 连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# Dubbo
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: cn.pings.web.admin

  # ApplicationConfig Bean
  application:
   id: pings-web-admin
   name: pings-web-admin

  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  # RegistryConfig Bean
  registry:
    id: client-admin
    address: zookeeper://zk_test:2181

# sys config
sys:
  # Service version
  service:
    version: 0.0.1
  jwt:
    secret: ==SFddfenfV2FuZzkyNjQ1NGRTQkFQSUpXVA==
     # 访问令牌过期时长(分钟)，<= 0时，使用默认配置5分钟
    access-token:
      expire-time: 3
    # 刷新令牌过期时长(分钟)，<= 0时，使用默认配置60分钟
    refresh-token:
      expire-time: 5